### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by jechaviz** [bootstrapguru/dexor#32]
Doesn't run:

Steps:
- composer global require bootstrapguru/droid
got:
`Changed current directory to C:/Users/jesus/AppData/Roaming/Composer
./composer.json has been updated
`
`
Running composer update bootstrapguru/droid
`
`
Loading composer repositories with package information
`
`
Updating dependencies
`
`
Nothing to modify in lock file
`
`
Writing lock file
`
`
Installing dependencies from lock file (including require-dev)
`
`
Nothing to install, update or remove
`
`
Generating autoload files
`
`
33 packages you are using are looking for funding.
`
`
Use the composer fund command to find out more!
`
`
No security vulnerability advisories found.
`
`
Using version ^1.1 for bootstrapguru/droid
`
- dexor
got:
`Warning: Undefined array key "HOME" in phar://C:/Users/jesus/AppData/Roaming/Composer/vendor/bootstrapguru/droid/builds/dexor/config/database.php on line 37
Warning: Undefined array key "HOME" in phar://C:/Users/jesus/AppData/Roaming/Composer/vendor/bootstrapguru/droid/builds/dexor/config/filesystems.php on line 12
Warning: Undefined array key "HOME" in phar://C:/Users/jesus/AppData/Roaming/Composer/vendor/bootstrapguru/droid/builds/dexor/config/filesystems.php on line 16
In database.php line 37:
  Undefined array key "HOME"
`
Other data:
`
OS: Windows 10
`
`
Terminal: cmd
`
`
PHP 8.3.9
`
`
Version: bootstrapguru/droid v1.1
`

**Comment by vijaythecoder** [comment]
Good news! We've implemented a fix for this issue.

A pull request has been created to address the problem with running the application on Windows due to the undefined 'HOME' environment variable. The fix implements cross-platform home directory detection to ensure compatibility with both Unix-like systems and Windows.

You can find the pull request here: #34

The fix includes changes to:
1. 
2. 

These changes allow the application to use both  and  to detect the home directory correctly on different operating systems.

Once this pull request is merged, we'll be able to release a new version soon. We appreciate your patience and for bringing this issue to our attention.

To test the fix (after it's merged and released):
1. Update your global installation of the package:
   
2. Run the 
   INFO  Nothing to migrate.  


In Interactivity.php line 32:
             
  Required.  
              command.

The application should now run without throwing any errors related to the 'HOME' environment variable.

Thank you for your contribution to improving Dexor!

**Comment by jechaviz** [comment]
What would the procedure to update with the new change?
I tried

**Comment by vijaythecoder** [comment]
The PR is currently merged to https://github.com/bootstrapguru/dexor/tree/dev-1.1.1 I am planning to release after some testing, hopefully by end of this week (~ Jul 6) If you want to get it sooner or help test this bug, you can follow the instructions below.

- Download the file: [dexor.zip](https://github.com/user-attachments/files/16409564/dexor.zip)
- Unzip and then move the file to the composer global bin directory

Let me know if you run into any issues with the new updated file.

**Comment by vijaythecoder** [comment]
@jechaviz did you get a chance to test the new build?
